/**
 * Tailwind brand acquisition.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { $brand, $fn, $json } from '../../../node_modules/@clevercanyon/utilities/dist/index.js';

// `__dirname` already exists when loaded by Tailwind via Jiti / commonjs.
// eslint-disable-next-line no-undef -- `__dirname` is not actually missing.
const projDir = path.resolve(__dirname, '../../..');

const pkgFile = path.resolve(projDir, './package.json');
const pkg = $json.parse(fs.readFileSync(pkgFile).toString());

/**
 * Acquires app’s brand for configuration of Tailwind themes.
 *
 * Jiti, which is used by Tailwind to load ESM config files, doesn’t support top-level await. Thus, we cannot use async
 * functionality here. Consider using a CLI request to acquire resources, if necessary. {@see https://o5p.me/1odhxy}.
 */
export default /* not async compatible */ () => {
    let brand = $fn.try(() => $brand.get(pkg.name), undefined)();
    if (brand) return brand; // That was’t such a chore, now was it?

    // Otherwise, we must have this to proceed below.
    if (!process.env._APP_BASE_URL) return; // Not possible.

    const brandConfig = $json.parse(execSync('./dev/.files/tailwind/cli-brand.mjs', { cwd: projDir }).toString());
    return $brand.addApp({ pkgName: pkg.name, baseURL: process.env._APP_BASE_URL, props: brandConfig });
};
