/**
 * Module preload plugin.
 *
 * Vite is not aware of this config file's location.
 *
 * @note PLEASE DO NOT EDIT THIS FILE!
 * @note This entire file will be updated automatically.
 * @note Instead of editing here, please review <https://github.com/clevercanyon/skeleton>.
 */

import { $str } from '../../../../../../../../node_modules/@clevercanyon/utilities/dist/index.js';

/**
 * Configures module preload plugin.
 *
 * @param   props Props from vite config file driver.
 *
 * @returns       Module preload plugin.
 */
export default async ({ appType, isSSRBuild }) => {
    const virtualId = 'vite/preload-helper.js';
    const resolvedVirtualId = '\0' + virtualId;

    return {
        name: 'vite-plugin-c10n-module-preload',
        enforce: 'pre', // Before Vite loads this virtual module.
        // {@see https://vite.dev/guide/using-plugins.html#enforcing-plugin-ordering}.
        // {@see https://vite.dev/guide/api-plugin.html#plugin-ordering}.

        load: {
            order: 'pre',
            handler: (id) => {
                if (id === resolvedVirtualId) {
                    if (['spa', 'mpa'].includes(appType) && !isSSRBuild) {
                        return $str.dedent(`
                            import { vitePreload } from '@clevercanyon/utilities/preact/components/head';
                            export const __vitePreload = vitePreload; // Preact module preloader.
                        `);
                    } else {
                        return 'export const __vitePreload = (dynamicImportFn, deps) => dynamicImportFn();';
                    }
                }
            },
        },
    };
};
